[package]
name = "uorm-samples"
version = "0.1.0"
edition = "2024"

[dependencies]
rivus-core = { version = "0.5.0", path = "../rivus/rivus-core" }
rivus-logger = { version = "0.5.0", path = "../rivus/rivus-logger" }
axum = "0.8.8"
uorm = { version = "0.5.0", path = "../uorm", features = ["mysql"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = "1.48.0"
anyhow = "1.0.100"
tracing = "0.1"
validator = { version = "0.20.0", features = ["derive"] }
serde_with = "3.16.1"
ctor = "0.6.3"
thiserror = "2.0.17"
rust-i18n = "3.1.5"

