
### 查询文件夹
GET http://{{host}}/folders/101
Content-Type: application/json


### 创建文件夹
POST http://{{host}}/folders/101
Content-Type: application/json

{
  "parentId": "1",
  "name": "test",
  "description": "test"
}